### ISSUE TITLE
Status always Unpair and Idle

### ISSUE THREAD

**Issue by ewwdeveloper** [AssemblyPayments/spi-client-java#14]
Hello,

I got the issue with pair. Right now I am using following sdk.

com.assemblypayments:spi-client-java:2.3.7

In this new sdk I am calling this method 
spi.setPosInfo("assembly", "2.3.7");

actually I don't know what is the actual value for "posVendorId" and "posVersion".

and also I don't know what will be the value for "TransactionOptions" in this method.

spi.initiatePurchaseTx(posRefId, Integer.parseInt(spInput[1]), tipAmount, cashoutAmount, promptForCashout,null);

so please help me to solve this issue.

**Comment by mgouline** [comment]
This issue was resolved offline, please contact your integration support directly with any further questions/issues.
